name: Conventional commit check

on:
  pull_request:
    branches: "main"

jobs:
  commit-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: commit-check/commit-check-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          message: true
          branch: false
          author-name: false
          author-email: false
          commit-signoff: false
          merge-base: false
          job-summary: true
          pr-comments: ${{ github.event_name == 'pull_request' }}

      - name: Send email notification
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME}}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Conventional Commits check failed
          to: ${{ secrets.EMAIL_DESTINATION }}
          from: GitHub Workflow
          body: Unfortunately, the Conventional Commits check has failed for PR ${{ github.event.pull_request.html_url }}