name: Nightly builds

on:
  pull_request:
    branches: [main]

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_SERVER=${{ secrets.MAIL_SERVER }}
          MAIL_PORT=${{ secrets.MAIL_PORT }}
          MAIL_FROM=${{ secrets.MAIL_FROM }}
          MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }}
          DOMAIN=${{ secrets.DOMAIN }}
          EOF

      - name: Set up Docker compose
        run: sudo apt-get install docker-compose

      - name: Docker compose up
        run: docker-compose up -d

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Manually install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest src/tests